import React, { useState, useEffect } from "react";

const subjects = [
  "Mathematics",
  "Science",
  "English",
  "Hindi",
  "SST",
  "Computer",
  "Marathi",
];

const topicsBySubject = {
  Science: ["Matter", "Atoms", "Light"],
  Mathematics: ["Algebra", "Geometry"],
};

export default function SmartTree() {
  const [subject, setSubject] = useState(null);
  const [topic, setTopic] = useState(null);
  const [stage, setStage] = useState("idle"); // explain | summary | notes
  const [aiText, setAiText] = useState("");

  useEffect(() => {
    if (stage !== "idle") {
      setAiText("🤖 AI is thinking...");
      setTimeout(() => {
        if (stage === "explain")
          setAiText(
            `This is a deep AI-guided explanation of ${topic}. Concepts are unlocked step-by-step like branches growing.`
          );
        if (stage === "summary")
          setAiText(`Key summary of ${topic} generated by Smart AI.`);
        if (stage === "notes")
          setAiText(
            `• Definition\n• Important points\n• Exam tips\n• Memory hooks`
          );
      }, 1200);
    }
  }, [stage, topic]);

  return (
    <div style={ui.wrapper}>
      <div style={ui.treeArea}>
        <div style={ui.trunk} />
        {subjects.map((s, i) => (
          <div
            key={s}
            style={{
              ...ui.branch,
              top: 40 + i * 55,
              background:
                subject === s
                  ? "linear-gradient(135deg,#6366f1,#22d3ee)"
                  : "rgba(255,255,255,0.6)",
            }}
            onClick={() => {
              setSubject(s);
              setTopic(null);
              setStage("idle");
            }}
          >
            {s}
          </div>
        ))}
      </div>

      <div style={ui.panel}>
        {!subject && (
          <div style={ui.hint}>Select a subject branch 🌿</div>
        )}

        {subject && !topic && (
          <>
            <h3 style={ui.title}>{subject} Topics</h3>
            <div style={ui.chips}>
              {(topicsBySubject[subject] || []).map((t) => (
                <button
                  key={t}
                  style={ui.chip}
                  onClick={() => setTopic(t)}
                >
                  {t}
                </button>
              ))}
            </div>
          </>
        )}

        {topic && (
          <>
            <div style={ui.aiBar}>🤖 Smart AI Active</div>

            <div style={ui.stageBtns}>
              <button onClick={() => setStage("explain")}>Explanation</button>
              <button onClick={() => setStage("summary")}>Summary</button>
              <button onClick={() => setStage("notes")}>Notes</button>
            </div>

            <div style={ui.output}>{aiText}</div>

            {stage === "notes" && (
              <button
                style={ui.copyBtn}
                onClick={() => navigator.clipboard.writeText(aiText)}
              >
                Copy to Concept Blocks
              </button>
            )}
          </>
        )}
      </div>
    </div>
  );
}
const ui = {
  wrapper: {
    minHeight: "100vh",
    display: "flex",
    background:
      "radial-gradient(circle at top,#eef2ff,#f8fafc 70%)",
    fontFamily: "Inter, sans-serif",
  },

  treeArea: {
    width: 280,
    padding: 24,
    position: "relative",
  },

  trunk: {
    position: "absolute",
    left: 30,
    top: 0,
    bottom: 0,
    width: 6,
    background: "linear-gradient(#94a3b8,#475569)",
    borderRadius: 8,
  },

  branch: {
    position: "relative",
    marginLeft: 50,
    padding: "10px 16px",
    borderRadius: 18,
    cursor: "pointer",
    marginBottom: 14,
    fontSize: 14,
    transition: "all 0.3s",
  },

  panel: {
    flex: 1,
    margin: 40,
    padding: 32,
    borderRadius: 28,
    background: "rgba(255,255,255,0.85)",
    boxShadow: "0 40px 120px rgba(0,0,0,0.08)",
  },

  title: {
    fontSize: 22,
    marginBottom: 14,
  },

  chips: {
    display: "flex",
    gap: 12,
  },

  chip: {
    padding: "10px 16px",
    borderRadius: 14,
    border: "none",
    background: "rgba(99,102,241,0.15)",
    cursor: "pointer",
  },

  aiBar: {
    marginBottom: 12,
    fontSize: 13,
    color: "#6366f1",
  },

  stageBtns: {
    display: "flex",
    gap: 10,
    marginBottom: 14,
  },

  output: {
    padding: 18,
    borderRadius: 20,
    background: "rgba(15,23,42,0.05)",
    minHeight: 120,
    fontSize: 15,
  },

  copyBtn: {
    marginTop: 14,
    padding: 12,
    borderRadius: 16,
    border: "none",
    background: "linear-gradient(135deg,#22d3ee,#6366f1)",
    cursor: "pointer",
    fontWeight: 600,
  },

  hint: {
    color: "#64748b",
    fontSize: 16,
  },
};
